[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/atlan-health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/slack/atlan-setup"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/health"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."netlify/functions/health"]
  runtime = "python3.8"
```
